QBShared = QBShared or {}
QBShared.ForceJobDefaultDutyAtLogin = true -- true: Force duty state to jobdefaultDuty | false: set duty state from database last saved
QBShared.Jobs = {
	unemployed = { label = 'Civilian', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Freelancer', payment = 50 } } },
	bus = { label = 'Bus', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 0 } } },
	judge = { label = 'Honorary', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Judge', payment = 0 } } },
	lawyer = { label = 'Law Firm', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Associate', payment = 0 } } },
	reporter = { label = 'Reporter', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Journalist', payment = 0 } } },
	trucker = { label = 'Trucker', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 0 } } },
	tow = { label = 'Towing', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Driver', payment = 0 } } },
	garbage = { label = 'Garbage', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Collector', payment = 0 } } },
	vineyard = { label = 'Vineyard', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Picker', payment = 0 } } },
	hotdog = { label = 'Hotdog', defaultDuty = true, offDutyPay = false, grades = { ['0'] = { name = 'Sales', payment = 0 } } },

	police = {
		label = 'Law Enforcement',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Cadet', payment = 30 },
			['1'] = { name = 'Officer', payment = 50 },
			['2'] = { name = 'Sergeant', payment = 60 },
			['3'] = { name = 'Staff Sergeant', payment = 70 },
			['4'] = { name = 'Corporal', payment = 80 },
			['5'] = { name = 'Master Corporal', payment = 90 },
			['6'] = { name = 'Warrant Officer', payment = 100 },
			['7'] = { name = 'Chief Warrant Officer', payment = 110 },
			['8'] = { name = 'Second Lieutenant', payment = 120 },
			['9'] = { name = 'First Lieutenant', payment = 130 },
			['10'] = { name = 'Captain', payment = 140 },
			['11'] = { name = 'Major', payment = 150 },
			['12'] = { name = 'Lieutenant Colonel', payment = 160 },
			['13'] = { name = 'Colonel', payment = 170 },
			['14'] = { name = 'Commander', payment = 180 },
			['15'] = { name = 'General', isboss = true, payment = 190 },
			['16'] = { name = 'Cadet', payment = 30 },
			['17'] = { name = 'Officer', payment = 50 },
			['18'] = { name = 'Sergeant', payment = 60 },
			['19'] = { name = 'Staff Sergeant', payment = 70 },
			['20'] = { name = 'Corporal', payment = 80 },
			['21'] = { name = 'Master Corporal', payment = 90 },
			['22'] = { name = 'Warrant Officer', payment = 100 },
			['23'] = { name = 'Chief Warrant Officer', payment = 110 },
			['24'] = { name = 'Second Lieutenant', payment = 120 },
			['25'] = { name = 'First Lieutenant', payment = 130 },
			['26'] = { name = 'Captain', payment = 140 },
			['27'] = { name = 'Major', payment = 150 },
			['28'] = { name = 'Lieutenant Colonel', payment = 160 },
			['29'] = { name = 'Colonel', payment = 170 },
			['30'] = { name = 'Commander', isboss = true, payment = 180 },
			['31'] = { name = 'General2', isboss = true, payment = 190 },
		},
	},
	bio = {
		label = 'Bio Medical Company',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Intern', payment = 0 },
			['1'] = { name = 'Technician', payment = 0 },
			['2'] = { name = 'Scientist', payment = 0 },
			['3'] = { name = 'Chief Biochemist', isboss = true, payment = 0 },
		},
	},
	mayfair = {
		label = 'Mayfair Tavern',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Security', payment = 0 },
			['1'] = { name = 'Bartender', payment = 0 },
			['2'] = { name = 'Head Security', payment = 0 },
			['3'] = { name = 'Nightclub Owner', isboss = true, payment = 0 },
		},
	},
	bcso = {
		label = 'National Guard',
		type = 'leo',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 0 },
			['1'] = { name = 'Officer', payment = 0 },
			['2'] = { name = 'Sergeant', payment = 0 },
			['3'] = { name = 'Lieutenant', payment = 0 },
			['4'] = { name = 'Sheriff', isboss = true, payment = 0 },
		},
	},
	firefighter = {
		label = 'Fire Department',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 0 },
			['1'] = { name = 'Firefighter', payment = 0 },
			['2'] = { name = 'Lieutenant', payment = 0 },
			['3'] = { name = 'Captain', payment = 0 },
			['4'] = { name = 'Chief', isboss = true, payment = 0 },
		},
	},
	ambulance = {
		label = 'EMS',
		type = 'ems',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 30 },
			['1'] = { name = 'Nurse', payment = 50 },
			['2'] = { name = 'Paramedic', payment = 70 },
			['3'] = { name = 'Doctor', payment = 90 },
			['4'] = { name = 'Specialist Physician', payment = 110 },
			['5'] = { name = 'General Practitioner', isboss = true, payment = 150 },
		},
	},
    realestate = {
           label = 'Real Estate',
           defaultDuty = true,
           offDutyPay = false,
           grades = {
                    ['0'] = { name = 'Employee', payment = 0 },
            },
    },	
    clerk = {
		label = 'Clerk',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Trainee',payment = 0 },
        	['1'] = {name = 'Clerk',payment = 0 },
        	['2'] = {name = 'Senior Clerk',payment = 0 },
        	['3'] = {name = 'Department Head',payment = 0 },
        	['4'] = {name = 'Director',payment = 0 },
        	['5'] = {name = 'Chief Executive Officer',isboss = true,payment = 0 },
    	},
    },
	taxi = {
		label = 'Taxi',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 0 },
			['1'] = { name = 'Driver', payment = 0 },
			['2'] = { name = 'Event Driver', payment = 0 },
			['3'] = { name = 'Sales', payment = 0 },
			['4'] = { name = 'Manager', isboss = true, payment = 0 },
		},
	},
	cardealer = {
		label = 'Vehicle Dealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 0 },
			['1'] = { name = 'Showroom Sales', payment = 0 },
			['2'] = { name = 'Business Sales', payment = 0 },
			['3'] = { name = 'Finance', payment = 0 },
			['4'] = { name = 'Manager', isboss = true, payment = 0 },
		},
	},
	mechanic = {
		label = 'Cyprus Mechanic',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Apprentice Mechanic', payment = 0 },
			['1'] = { name = 'Junior Mechanic', payment = 0 },
			['2'] = { name = 'Mechanic', payment = 0 },
			['3'] = { name = 'Senior Mechanic', payment = 0 },
			['4'] = { name = 'Shop Foreman', payment = 0 },
			['5'] = { name = 'Boss', isboss = true, payment = 0 },
		},
	},
	mechanic2 = {
		label = 'Bay Are Customs',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 0 },
			['1'] = { name = 'Novice', payment = 0 },
			['2'] = { name = 'Experienced', payment = 0 },
			['3'] = { name = 'Advanced', payment = 0 },
			['4'] = { name = 'Manager', isboss = true, payment = 0 },
		},
	},
	mechanic3 = {
		label = '187 Motorcycle',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 0 },
			['1'] = { name = 'Novice', payment = 0 },
			['2'] = { name = 'Experienced', payment = 0 },
			['3'] = { name = 'Advanced', payment = 0 },
			['4'] = { name = 'Manager', isboss = true, payment = 0 },
		},
	},
	beeker = {
		label = 'Beeker\'s Garage',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 0 },
			['1'] = { name = 'Novice', payment = 0 },
			['2'] = { name = 'Experienced', payment = 0 },
			['3'] = { name = 'Advanced', payment = 0 },
			['4'] = { name = 'Manager', isboss = true, payment = 0 },
		},
	},
	farmer = {
	label = 'Farmer',
	defaultDuty = true,
	offDutyPay = false,
	grades = {
		['0'] = { name = 'Apprentice', payment = 0 },
		['1'] = { name = 'Field Worker', payment = 0 },
		['2'] = { name = 'Harvester', payment = 0 },
		['3'] = { name = 'Supervisor', payment = 0 },
		['4'] = { name = 'Farm Owner', isboss = true, payment = 0 },
		},
	},
	brewery = {
	label = 'Brewery',
	defaultDuty = true,
	offDutyPay = false,
	grades = {
		['0'] = { name = 'Trainee Brewer', payment = 0 },
		['1'] = { name = 'Assistant Brewer', payment = 0 },
		['2'] = { name = 'Brew Specialist', payment = 0 },
		['3'] = { name = 'Brewmaster', payment = 0 },
		['4'] = { name = 'Head Brewer', isboss = true, payment = 0 },
		},
	},
	kooni = {
    label = 'Kooni Group',
	defaultDuty = true,
	offDutyPay = false,
    grades = {
        ['0'] = { name = 'Financier', payment = 0 },
        ['1'] = { name = 'Contractor', payment = 0},
        ['2'] = { name = 'Rookie', payment = 0},
	    ['3'] = { name = 'Elite', payment = 0},
        ['4'] = { name = 'Site Commander', payment = 0},
        ['5'] = { name = 'Second In Command/Team Leader', payment = 0},
        ['6'] = { name = 'Captain', payment = 0 },
        ['7'] = { name = 'Commander', isboss = true, payment = 0 },
        },
    },
    nightrunner = {
        label = 'Night Runners Crew',
		defaultDuty = true,
		offDutyPay = false,
        grades = {
            ['0'] = { name = 'Racer', payment = 0 },
            ['1'] = { name = 'Ofiicial Member', payment = 0 },
            ['2'] = { name = 'Financier', payment = 0 },
            ['3'] = { name = 'SGT AT ARMS', payment = 0 },
            ['4'] = { name = 'Road Captain', payment = 0 },
            ['5'] = { name = 'Commander', payment = 0 },
            ['6'] = { name = 'Founder', isboss = true, payment = 0 },
        },
    },
    EME = {
		label = "Mexican Mafia",
		defaultDuty = true,
		offDutyPay = false,
        grades = {
            ['0'] = { name = 'Outsider', payment = 0  },
            ['1'] = { name = 'Affiliated', payment = 0  },
            ['2'] = { name = 'Trouble Maker', payment = 0  },
            ['3'] = { name = 'Pee Wee', payment = 0 },
            ['4'] = { name = 'Veteran', payment = 0 },
            ['5'] = { name = 'Original Gangster', payment = 0 },
            ['6'] = { name = 'Made Man', payment = 0 },
            ['7'] = { name = 'Mesa', isboss = true, payment = 0 },
        },
    },

	burgershot = {
	label = 'Burger Shot',
    type = "burgershot",
	defaultDuty = true,
	offDutyPay = false,
	grades = {
			['0'] = { name = 'Employee', payment = 0 },
			['1'] = { name = 'Employer', isboss = false, payment = 0 },
			['2'] = { name = 'Head Cheff', isboss = false, payment = 0 },
			['3'] = { name = 'Manager', isboss = true, payment = 0 },
			['4'] = { name = 'Owner', isboss = true, payment = 0 },
		},
	},
	burgershot2 = {
	label = 'Harleys Noodle Haven',
    type = "burgershot2",
	defaultDuty = true,
	offDutyPay = false,
	grades = {
			['0'] = { name = 'Employee', payment = 0 },
			['1'] = { name = 'Employer', isboss = false, payment = 0 },
			['2'] = { name = 'Chef', isboss = false, payment = 0 },
			['3'] = { name = 'Manager', isboss = true, payment = 0 },
			['4'] = { name = 'Owner', isboss = true, payment = 0 },
		},
	},
	mining = {
	label = 'Mining',
    type = "Mining",
	defaultDuty = true,
	offDutyPay = false,
	grades = {
			['0'] = { name = 'Amateur', payment = 0 },
			['1'] = { name = 'Miner', isboss = false, payment = 0 },
			['2'] = { name = 'Head Miner', isboss = false, payment = 0 },
			['3'] = { name = 'Manager', isboss = true, payment = 0 },
			['4'] = { name = 'Chief', isboss = true, payment = 0 },
		},
	},
	bennys = {
		label = 'Benny\'s Original Motor Works',
		type = 'mechanic',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 0 },
			['1'] = { name = 'Novice', payment = 0 },
			['2'] = { name = 'Experienced', payment = 0 },
			['3'] = { name = 'Advanced', payment = 0 },
			['4'] = { name = 'Manager', isboss = true, payment = 0 },
		},
	},

	casino = {
		label = 'Kooni Casino',
		type = 'casino',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 0 },
			['1'] = { name = 'Novice', payment = 0 },
			['2'] = { name = 'Experienced', payment = 0 },
			['3'] = { name = 'Advanced', payment = 0 },
			['4'] = { name = 'Manager', isboss = true, payment = 0 },
		},
	},

		cardealer2 = {
		label = 'The Syndicate',
		type = 'cardealer',
		defaultDuty = true,
		offDutyPay = false,
		grades = {
			['0'] = { name = 'Recruit', payment = 0 },
			['1'] = { name = 'Novice', payment = 0 },
			['2'] = { name = 'Experienced', payment = 0 },
			['3'] = { name = 'Advanced', payment = 0 },
			['4'] = { name = 'Manager', isboss = true, payment = 0 },
		},
	},
	
}
