---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hertzeil.
--- DateTime: 31/08/2023 01:45:22
---

Config = {}
Config.Min = {
    x = -20000.0,
    y = -20000.0,
    z = -10000.0
}
Config.Max = {
    x = 20000.0,
    y = 20000.0,
    z = 10000.0
}
