

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hertzeil.
--- DateTime: 31/08/2023 01:43:42
---

fx_version 'cerulean'
games { 'gta5' }
lua54 'yes'
author 'Hertzeil'

description 'Remove boundary limits - Fivem Version'
version '1.0.0'

client_scripts {
    'config.lua',
    'client/main.lua'
}
