---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hertzeil.
--- DateTime: 31/08/2023 01:44:12
---

AddEventHandler('onClientResourceStart', function(resourceName)
    if GetCurrentResourceName() ~= resourceName then return end

    ExtendWorldBoundaryForPlayer(Config.Min.x, Config.Min.y, Config.Min.z)
    ExtendWorldBoundaryForPlayer(Config.Max.x, Config.Max.y, Config.Max.z)
end)
